openapi: 3.0.1
info:
  title: Testkube Pro API
  description: API for Testkube Pro
  contact:
    email: testkube@kubeshop.io
  license:
    name: COMMERICAL
    url: https://opensource.org/licenses/MIT
  version: cloud-api/1.10.51
paths:
  /organizations/{id}/environments/{environmentID}/features:
    get:
      summary: Get environment features
      description: Get environment features
      operationId: getEnvironmentFeatures
      responses:
        '200':
          $ref: './components.yaml#/components/responses/EnvironmentFeatures'
        '400':
          $ref: './components.yaml#/components/responses/BadRequestError'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './components.yaml#/components/responses/NotFoundError'
      security:
        - BearerAuth: []
    patch:
      summary: Patch environment features
      description: Endpoint for updating environment features
      operationId: patchEnvironmentFeatures
      requestBody:
        $ref: './components.yaml#/components/requestBodies/EnvironmentFeatures'
      responses:
        '200':
          $ref: './components.yaml#/components/responses/NoBody'
        '400':
          $ref: './components.yaml#/components/responses/BadRequestError'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './components.yaml#/components/responses/NotFoundError'
      security:
        - BearerAuth: []
    parameters:
      - $ref: './components.yaml#/components/parameters/ID'
      - $ref: './components.yaml#/components/parameters/EnvironmentID'
