openapi: 3.0.1
info:
  title: Testkube Pro API
  description: API for Testkube Pro
  contact:
    email: testkube@kubeshop.io
  license:
    name: COMMERICAL
    url: https://opensource.org/licenses/MIT
  version: cloud-api/1.10.51
paths:
  /organizations/{id}/settings:
    get:
      summary: Features info, global for Testkube Pro or Enterprise
      description: Get API info like current version
      operationId: getOrganizationSettings
      responses:
        '200':
          $ref: './components.yaml#/components/responses/Settings'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'
    patch:
      summary: Update setting for given parameter
      description: >-
        Update setting for given parameter, you can choose from org, env, or
        user
      operationId: updateOrganizationSetting
      requestBody:
        $ref: './components.yaml#/components/requestBodies/SettingUpsert'
      responses:
        '200':
          $ref: './components.yaml#/components/responses/Setting'
        '400':
          $ref: './components.yaml#/components/responses/BadRequestError'
        '405':
          $ref: './components.yaml#/components/responses/MethodNotAllowedError'
        '500':
          $ref: './components.yaml#/components/responses/InternalServerError'
    parameters:
      - $ref: './components.yaml#/components/parameters/ID'
